function getRandomElement(arr: string[]) {
  return arr[Math.floor(Math.random() * arr.length)];
}

export default function generateUsername() {
  const adjectives = [
    "Fuzzy",
    "Wacky",
    "Zany",
    "Goofy",
    "Silly",
    "Loopy",
    "Quirky",
    "Funky",
    "Nutty",
    "Bouncy",
    "Fluffy",
    "Clumsy",
    "Jolly",
    "Snoozy",
    "Crazy",
    "Bizarre",
    "Spunky",
    "Wobbly",
    "Grumpy",
    "Dizzy",
    "Whacky",
    "Puffy",
    "Snazzy",
    "Dorky",
    "Jumpy",
    "Twitchy",
    "Nifty",
    "Cuddly",
    "Whiskery",
    "Frizzy",
    "Slinky",
    "Witty",
    "Whimsy",
    "Cranky",
    "Mushy",
    "Frothy",
    "Cheeky",
    "Giggly",
    "Nimble",
    "Hoppy",
  ];

  const nouns = [
    "Penguin",
    "Banana",
    "Wombat",
    "Pancake",
    "Ostrich",
    "Muffin",
    "Lobster",
    "Potato",
    "Sloth",
    "Pickle",
    "Unicorn",
    "Cupcake",
    "Marshmallow",
    "Octopus",
    "Doughnut",
    "Koala",
    "Squid",
    "Taco",
    "Pudding",
    "Giraffe",
    "Mongoose",
    "Walrus",
    "Pineapple",
    "Hedgehog",
    "Cupcake",
    "Beaver",
    "Biscuit",
    "Platypus",
    "Chipmunk",
    "Cucumber",
    "Pelican",
    "Gnome",
    "Coconut",
    "Llama",
    "Waffle",
    "Peanut",
    "Toadstool",
    "Crumpet",
    "Yak",
    "Seahorse",
  ];

  const adjective = getRandomElement(adjectives);
  const noun = getRandomElement(nouns);
  const number = Math.floor(Math.random() * 100);

  return `${adjective}${noun}${number}`;
}
